name: tango
description: Tango is a flexible build configuration tool that is the perfect partner for your Flutter project. Setup different build variants like paid/free or development/production. Tango handles copying of files, scaling images for different screen resolutions. 
version: 0.1.1
homepage: https://github.com/marnberg/tango
executables:
  tango:

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  # https://pub.dev/packages/image
  image: ^2.1.12

  # https://pub.dev/packages/args
  args: ^1.5.2

  # https://pub.dev/packages/yaml
  yaml: ^2.2.0

dev_dependencies:
  # https://pub.dev/packages/pedantic
  pedantic: ^1.9.0

  # https://pub.dev/packages/test
  test: ^1.6.0

  # https://pub.dev/packages/mockito
  mockito: ^4.1.1
